[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/api/team-members"
  to = "/.netlify/functions/team-members"
  status = 200